heat_template_version: 2014-10-16

description: Un serveur simple qui lance un script python

parameters:
  image:
    type: string
    description: Image utilisee pour les serveurs
    default: INF4410-Ubuntu-trusty-mini

  flavor:
    type: string
    description: Flavor utilisee par les serveurs
    default: INF4410-mini

  subnet_id:
    type: string
    description: Sous-reseau dans lequel le load balancer sera situe
    default: inf4410-net

  mykey:
    type: string
    description: Clé ssh
    default: serverkey

resources:
  server:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: mykey }
      networks: [{network: {get_param: subnet_id}}]
      image: { get_param: image }
      flavor: { get_param: flavor }
      user_data_format: RAW
      user_data: |
            #!/bin/bash
            curl -O https://raw.githubusercontent.com/houssemmh/INF4410-TP3/master/server.py
            python server.py 



outputs:
  server_networks:
    description: The networks of the deployed server
    value: { get_attr: [server_nodes, networks] }